apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fleet-operator.fullname" . }}-manager-role
  labels:
  {{- include "fleet-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fleet.roboscale.io
  resources:
  - fleets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fleet.roboscale.io
  resources:
  - fleets/finalizers
  verbs:
  - update
- apiGroups:
  - fleet.roboscale.io
  resources:
  - fleets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - robot.roboscale.io
  resources:
  - discoveryservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - robot.roboscale.io
  resources:
  - robots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - types.kubefed.io
  resources:
  - federatednamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fleet-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fleet-operator
    app.kubernetes.io/part-of: fleet-operator
  {{- include "fleet-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "fleet-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "fleet-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'