apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "fleet-operator.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "fleet-operator.fullname" . }}-serving-cert
  labels:
  {{- include "fleet-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "fleet-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-fleet-roboscale-io-v1alpha1-fleet
  failurePolicy: Fail
  name: vfleet.kb.io
  rules:
  - apiGroups:
    - fleet.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - fleets
  sideEffects: None