name: Story
description: Describe the high-level requirements or use-cases for robots
labels: ["story"]
body:
  - type: textarea
    id: story
    attributes:
      label: "The Story"
    validations:
      required: true

  - type: textarea
    id: related-story
    attributes:
      label: Related Story
    validations:
      required: true

  - type: textarea
    id: parent-story
    attributes:
      label: Related Technical Story
    validations:
      required: true